import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import { getServerSession } from '@/server/auth-options';
import LogoutButton from '@/components/logout-button';
import LoginRegisterModal from '@/components/modals/login-register-modal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface Props {
	children: ReactNode;
}

export default
async function RootLayout(props: Props) {
	const { children } = props;
	const session = await getServerSession();

	return (<html lang="en">
		<body className={inter.className}>
			<header className="bg-gray-800 py-4">
				<nav className="container mx-auto flex justify-between items-center">
					<h1 className="text-white font-bold text-xl">Choose Your Own Adventure</h1>
					<div>
						{session && (
							<LogoutButton />
						)}
						{!session && (
							<LoginRegisterModal/>
						)}
					</div>
				</nav>
			</header>
			<main className="flex-1">
				{children}
			</main>
		</body>
	</html>
	);
}
