import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface Props {
	children: ReactNode;
	modal: ReactNode;
}

export default function RootLayout(props: Props) {
	const {
		children,
		modal,
	} = props;

	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
				{modal}
			</body>
		</html>
	);
}
