/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6KBhKBw
 */
import { DbStory, UiStory } from '@/common/types/Story';
import {
	CardContent,
	CardTitle,
	CardDescription,
	CardHeader,
	Card,
	CardFooter,
} from '@/components/ui/card';

interface Props {
	story: DbStory | UiStory;
}

export function StoryCard(props: Props) {
	const {
		story: {
			title,
			summary,
			ownerUsername,
		},
	} = props;
	return (
		<Card>
			<CardHeader>
				<CardTitle>{title}</CardTitle>
				<CardDescription>{summary}</CardDescription>
			</CardHeader>
			<CardContent>
				<p>asdfasdfasddlfjdslfj</p>
			</CardContent>
			<CardFooter>
				<p>by {ownerUsername}</p>
			</CardFooter>
		</Card>
	);
}
